// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBShtEfau6T1bTj6EwRdqgNmQbdwTZ0-wU',
    appId: '1:786156777104:web:a1af3b7d0fe2853d16f215',
    messagingSenderId: '786156777104',
    projectId: 'emotionchat-426f4',
    authDomain: 'emotionchat-426f4.firebaseapp.com',
    storageBucket: 'emotionchat-426f4.appspot.com',
    measurementId: 'G-MVCNDKVXMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEQ2VAqJtwHy1Oubr8JZpFYfFrmp3T4nI',
    appId: '1:786156777104:android:46f87ddce9b2e8f616f215',
    messagingSenderId: '786156777104',
    projectId: 'emotionchat-426f4',
    storageBucket: 'emotionchat-426f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-QTJE5F-tSfaIrv8_3mQBVbPGkk8ofzE',
    appId: '1:786156777104:ios:f408d54816f91a4f16f215',
    messagingSenderId: '786156777104',
    projectId: 'emotionchat-426f4',
    storageBucket: 'emotionchat-426f4.appspot.com',
    iosBundleId: 'com.example.emotionChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-QTJE5F-tSfaIrv8_3mQBVbPGkk8ofzE',
    appId: '1:786156777104:ios:350db83a0c45eebf16f215',
    messagingSenderId: '786156777104',
    projectId: 'emotionchat-426f4',
    storageBucket: 'emotionchat-426f4.appspot.com',
    iosBundleId: 'com.example.emotionChat.RunnerTests',
  );
}
